FROM node:16
# ruleid: docker-npm-install-without-registry
RUN npm install unclaimed-package-h --registry=https://registry.npmjs.org/


# ruleid: docker-npm-install-without-registry
RUN npm install unclaimed-package-i

RUN npm install unclaimed-package-j \
                another-library \
                something-something-testing-library \
                react

npm install @testorg/unclaimed-package-k